image:
  file: .gitpod.Dockerfile

tasks:
  - init: python -m virtualenv env && \
      source env/bin/activate && \
      pip install -U pip wheel setuptools && \
      pip install -e . && \
      pip install -r requirements-test.txt && \
      npm install -g jshint stylelint
